POST http://localhost:3000/reportes
Content-Type: application/json

{
  "tipo": "Infraestructura",
  "descripcion": "Daño en alumbrado público"
}


### reporte
GET http://localhost:3000/reportes


### Ejemplo 2
POST http://localhost:3000/reportes
Content-Type: application/json

{
  "tipo": "Ambiente",
  "descripcion": "Acumulación de residuos en una zona comunitaria"
}